### ISSUE TITLE
Watchlist element name from code instead of query params

### ISSUE THREAD

**Issue by levydanqc** [levydanqc/stockaccino#45]
Lorsqu'un stock est ajouté à la watchlist, le query params est enregistré au lieu du code de la compagnie.
Cela fait en sorte qu'en cas de stock recherché à la main (i.e.: http://localhost:4200/search?searchedStock=tsla) et ensuite ajouté à la watchlist, le nom du stock dans la watchlist est "tsla" plutôt que "TSLA". Donc il faut plutôt  enregistrer dans la watchlist le code de la requête http que le stock dans l'url

**Comment by OlivierPoitras** [comment]
c'est réglé dans la pr de JWT
