### ISSUE TITLE
`OPTIONAL` Improve search bar for enabling term like "apple" and "tesla".

### ISSUE THREAD

**Issue by levydanqc** [levydanqc/stockaccino#52]

**Comment by levydanqc** [comment]
@OlivierPoitras Pourquoi as tu close cette issue?

**Comment by OlivierPoitras** [comment]
Ca devrait aller dans le trello, pas dans issues, c'est une amelioration de fonctionnalité qui se ferait en cas de surplus de temps, donc ca devrait être dans le backlog, pas dans les issues je crois
