### ISSUE TITLE
Prevent empty api call for checking email

### ISSUE THREAD

**Issue by levydanqc** [levydanqc/stockaccino#67]
In signup page, if there's no email in input -> every time we focus/unfocus from field it calls the api and return a 401 (failed) response.
We should add a condition when calling `https://localhost:7056/users/{email}` to verify there's an input (a valid one)

**Comment by levydanqc** [comment]
Just saw that's because it call the get on `https://localhost:7056/users` (because there's no input) instead of `https://localhost:7056/users/{email}` and the first endpoint needs to be authorized but the second don't

**Comment by OlivierPoitras** [comment]
Fixed, added validation
